### ISSUE TITLE
Aster can determine the Iris GeoTiff zip URL

### ISSUE THREAD

**Issue by little9** [curationexperts/aster#27]
Iris already includes the URL to the show page when you run the importer.

This is stored in the `dct_refernces_t` JSON as a http://schema.org/url attribute: http://iris-demo.curationexperts.com/concern/vector_works/7d278t00k

That was hidden on the Aster show page in curationexperts/aster#23

The download URL uses the `FileSet` id: 

http://iris-demo.curationexperts.com/downloads/4j03cz64w?locale=en

This URL is correct for Shapefiles, but there will need to be a different URL for GeoTiffs. 

ACCEPTANCE CRITERIA
------------------------------

- [x] Aster can determine/generate or store the Iris URL for the GeoTiff zip download

**Comment by little9** [comment]
This depends on curationexperts/iris#66 being completed

**Comment by val99erie** [comment]
For story curationexperts/iris#66, I ended up editing the `downloadURL` in the existing `dct_references_s` field in the geoblacklight solr document so that the download link will be for the zip file instead of for the representative file.  The `downloadURL` is the link that is automatically picked up by `geoblacklight` views, so there are no code changes needed in Aster.  I'll close this story as complete.
